Feature/mpi halo resize
MetOffice/orca-jedi pull request #96
Opened 2024-06-12 14:40 UTC by twsearle

## Description

Changes to update tests for compatibility with the new atlas-orca mesh generator halo = 1.

## Issue(s) addressed

Part of https://github.com/ecmwf/atlas-orca/issues/19

## Dependencies

- [ ] jjdocs change for testing in sith https://github.com/MetOffice/jjdocs/pull/167
- [ ] atlas-orca change to introduce halo > 0 mesh generation https://github.com/ecmwf/atlas-orca/pull/20

## Impact

Enable domain distributed MPI for improved performance of high resolution models.

## Checklist

- [x] I have updated the unit tests to cover the change
- [x] New functions are documented briefly via Doxygen comments in the code
- [x] I have linted my code using cpplint
- [ ] I have run the unit tests
- [ ] I have run mo-bundle to check integration with the rest of JEDI and run the unit tests under all environments

2024-06-12 21:47 UTC, s-good requested changes
Looks great, thanks. Just one small syntax error to fix.

2024-06-19 08:11 UTC, twsearle commented on src/orca-jedi/geometry/Geometry.cc
> +         && ( (halo > 0) ) {
done!

2024-06-19 09:58 UTC, s-good approved these changes

2024-07-30 08:03 UTC, twsearle commented
Closing this one as it is superceded by the approach in MetOffice/orca-jedi/issues/109

2024-07-30 08:03 UTC, closed without merging